export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    TEXT = "text/plain",
    XML = "application/xml",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    BMP = "image/bmp",
    SVG = "image/svg+xml",
    ICO = "image/x-icon",
    WAV = "audio/wav",
    MP3 = "audio/mpeg",
    MP4 = "video/mp4",
    WEBM = "video/webm",
    OGG = "application/ogg",
    ZIP = "application/zip",
    PDF = "application/pdf",
    CSV = "text/csv"
}